### ISSUE TITLE
Not working with Discord.js v14

### ISSUE THREAD

**Issue by sfarmani** [SakiyaDev/anti-phish-advanced#11]
This package seems to not work with Discord.js v14
Probably due to permission bit fields not being updated?

When I stop using this package, it doesn't crash my bot

```
at Receiver.receiverOnMessage (C:\Discord-Bots\test-bot\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:84:10)
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: SEND_MESSAGES.
    at Function.resolve (C:\Discord-Bots\test-bot\node_modules\discord.js\src\util\BitField.js:170:11)
    at C:\Discord-Bots\test-bot\node_modules\discord.js\src\util\BitField.js:165:54
    at Array.map (<anonymous>)
    at Function.resolve (C:\Discord-Bots\test-bot\node_modules\discord.js\src\util\BitField.js:165:40)
    at Client.generateInvite (C:\Discord-Bots\test-bot\node_modules\discord.js\src\client\Client.js:436:47)
    at Fish.checkForFish (C:\Discord-Bots\test-bot\node_modules\anti-phish-advanced\lib\classes\fish.js:36:59)
    at Client.<anonymous> (C:\Discord-Bots\test-bot\node_modules\anti-phish-advanced\lib\classes\fish.js:17:18)
    at Client.emit (node:events:406:35)
    at MessageCreateAction.handle (C:\Discord-Bots\test-bot\node_modules\discord.js\src\client\actions\MessageCreate.js:28:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Discord-Bots\test-bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Discord-Bots\test-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Discord-Bots\test-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:494:22)
    at WebSocketShard.onMessage (C:\Discord-Bots\test-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Discord-Bots\test-bot\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Discord-Bots\test-bot\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:394:28)
    at Receiver.receiverOnMessage (C:\Discord-Bots\test-bot\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:394:28)
    at Receiver.dataMessage (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (C:\Discord-Bots\test-bot\node_modules\ws\lib\receiver.js:84:10) {
  code: 'BitFieldInvalid'
}
```

**Comment by EmiliaShiori** [comment]
Fixed in the pull request the was just merged.
