### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wreaking** [SakiyaDev/anti-phish-advanced#2]
Well uhh there is an error occurring in events because I'm using the old version of djsV12. So is your package still doesn't support the old version? if yes, it isn't working for me.

**Comment by tsukuyomiotoko** [comment]
Hey, could you be more specific as to what error you're getting? Thank you.

It would be helpful if you sent the error message as well as the discord.js version you're using!

**Comment by APOORVBG** [comment]
> 
he means you said anti-phish advanced works for v12 discord.js 
(you said here:  https://github.com/SakiyaDev/anti-phish-implementation   
in important section)
but it throws error of intents    
is it even supported for v12???

**Comment by Wreaking** [comment]
it says
```
Error: Cannot find module 'node:events'
Require stack:
- /home/runner/Name-your-repl/node_modules/anti-phish-advanced/node_modules/discord.js/src/client/BaseClient.js
- /home/runner/Name-your-repl/node_modules/anti-phish-advanced/node_modules/discord.js/src/index.js
- /home/runner/Name-your-repl/node_modules/anti-phish-advanced/lib/classes/fish.js
- /home/runner/Name-your-repl/node_modules/anti-phish-advanced/lib/index.js
- /home/runner/Name-your-repl/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/Name-your-repl/node_modules/anti-phish-advanced/node_modules/discord.js/src/client/BaseClient.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    ```

**Comment by tsukuyomiotoko** [comment]
Huh that's weird, super sorry for the late reply. I'll check it out, thought it might just be a repl issue. Not sure, I'll let you know!
